#!/usr/bin/env python3
"""Animate the target chromosone frames generated by the project.

Usage:
    python3 animate_targets.py --delay 0.1

This script imports the target-generation helpers from `main.py` and uses
`plot_spider_pose` to display each frame for `delay` seconds.
"""
import argparse
import math
import matplotlib.pyplot as plt

from main import createTargetChromosone, createTargetChromosoneList
from plot_spider_pose import plot_spider_pose


def animate(chrom_list, delay=0.1):
    """Animate a list of chromosones using plot_spider_pose.

    Each frame is shown for `delay` seconds. Uses non-blocking show where
    supported and closes the figure between frames to keep windows tidy.
    """
    orig_show = plt.show

    def _non_blocking_show(*args, **kwargs):
        try:
            return orig_show(block=False)
        except TypeError:
            return orig_show(*args, **kwargs)

    plt.show = _non_blocking_show
    try:
        for idx, chrom in enumerate(chrom_list):
            print(f"Animating frame {idx+1}/{len(chrom_list)}")
            plot_spider_pose(chrom)
            try:
                plt.pause(delay)
                plt.close()
            except Exception:
                # Some backends may not support pause/close; ignore and continue
                pass
    finally:
        plt.show = orig_show


def build_targets():
    # Match how main creates the two poses
    A = createTargetChromosone(math.radians(0), math.radians(-45), math.radians(-30), True)
    B = createTargetChromosone(math.radians(20), math.radians(-45), math.radians(-30), False)
    frames = createTargetChromosoneList(A, B)
    return frames


def main():
    parser = argparse.ArgumentParser(description='Animate target chromosone frames')
    parser.add_argument('--delay', type=float, default=0.1, help='seconds to display each frame')
    parser.add_argument('--count', type=int, default=0, help='If >0, animate only the first N frames')
    args = parser.parse_args()

    frames = build_targets()
    if args.count > 0:
        frames = frames[:args.count]

    animate(frames, delay=args.delay)


if __name__ == '__main__':
    main()
