
from spider_pose import plot_spider_pose
from genetic_algorithm import animateTargetChromosomes, runGA
from nn_self import genRanPoses, Full_NN
from nn_pytorch import run_pytorch_nn
from matplotlib import pyplot as plt


#Main helper functions for displaying steps in main.py
def display_creating_target_chromosomes():
    """
    Upon setting the poses, we will progress to running the createTargetChromosomeList function, which takes in the two poses as parameters and returns 
    a variable called GATargetPoses. This variable also displays/plots the two poses, A and B.
    """

    print("\n" + "="*60)
    print("STEP 1: Creating and Displaying Target Chromosomes")
    print("="*60)

def display_generating_input_data(GATargetPoses):
    """
    progressing further into the main program we run a helper function called display_generating_input_data(GATargetPoses) this function prints 
    out step 2 that animates the target chromosomes. after displaying text it will ask the user if they want to animate the target chromosomes or not, 
    if the user inputs 'y' it will animate the target chromosomes. and if they press n it will skip the animation. and progress to step 3. if animation 
    is chosen the animation will iterate from pose A to pose B and back to pose A for 3 cycles. The function also returns maxGenerations, populationSize and 
    mutationRate variables that are used in the genetic algorithm, as the user is required to input data for these variables.
    """

    print(f"\nGenerated {len(GATargetPoses)} target frames for full walk cycle.")

    print("\n" + "="*60)
    print("STEP 2: Animate Target Chromosomes")
    print("="*60)

    choice = input("Do you want to animate the target chromosomes? (y/n): ").lower()
    if choice == 'y':
        print("Animating target chromosomes...")
        animateTargetChromosomes("Target Chromosomes", GATargetPoses, delay=0.01) 
        print("Animation complete.")

    print("\n" + "="*60)
    print("STEP 3: Running Genetic Algorithm")
    print("="*60)

    maxGenerations = int(input("Enter the maximum number of generations for the GA (Recommended: 300): "))
    populationSize = int(input("Enter the population size for the GA (Recommended: 300): "))
    mutationRate = float(input("Enter the mutation rate for the GA (Recommended 0.01): ")) 

    return maxGenerations, populationSize, mutationRate

def run_genetic_algorithm(maxGenerations, populationSize, mutationRate, GATargetPoses):
    """
    When the user inputs the required data, the main program will progress to running the genetic algorithm function called run_genetic_algorithm(GATargetPoses, 
    maxGenerations, populationSize, mutationRate). This function takes in the target poses and the user-inputted parameters and runs the genetic algorithm to generate 
    a walking gait for the spider robot. it returns a variable called bestChromosome which is the best solution found by the genetic algorithm.
    """

    print("\nRunning GA to match target poses...")
    GAPoses = runGA(maxGenerations, populationSize, mutationRate, GATargetPoses)
    print("GA Complete!")
    return GAPoses

def display_animating_ga_generated_poses(GAPoses):
    """
    display_animating_ga_generated_poses(GAPose) is the next helper function that is run in the main and prints out step 4 and runs animateTagetChromosomes(GAPose, delay) 
    and returns animateTargetChromosomes function.
    """

    print("\n" + "="*100)
    print("STEP 4: Animate GA Generated Poses")
    print("="*100)
    print("Animating GA-generated poses...")
    animateTargetChromosomes("GA Chromosome", GAPoses, delay=0.1)
    print("Animation complete.")
    return animateTargetChromosomes

def generate_random_pose(GAPoses):
    """
    generate_random_pose counts the number of poses generated by the genetic algorithm, from here it will print out text that specifies 
    how many random input poses have been generated for the neural network training. It will then create a variable called inputData that 
    is returned from genRandomPoses with the population size set to the number of poses generated by the genetic algorithm.
    """

    num_poses = len(GAPoses)
    print(f"\nGenerating {num_poses} random input poses for neural network training...")
    inputData = genRanPoses(popSize=num_poses)
    print("Input data generated.")
    return inputData

# ============ Custom Neural Network Training =============

def train_custom_nn(inputData, GAPoses):
    """
    This section will progress to training the custom neural network. to start off the section step 5 within the helper function of train_custom_nn(inputData, GAPoses). 

    In this function it fistly prints out the text for step 5 and then creates a variable nn that stores the full neural network as Full_NN(x (input layer size), h (hidden layer size), y (output layer size)). 
    the input layer size is set to 24, hidden layer size is set to [512, 256] and output layer size is set to 24.

    within the same helper function it declares nn.train_nn(x = inputData, target = GAPoses, epochs = 1000, lr = 0.01) this is where the neural netwrok is 
    trained with the input data and target data from the genetic algorithm poses as the target data. the epochs is how many times the neural netwrok will 
    iterate over the traing data. lr is the learning rate it determins how much to change the model in response to the estimated error each time the model 
    weights are updated.
    """

    print("\n" + "="*100)
    print("STEP 5: Training Custom Neural Network")
    print("="*100)
    
    nn = Full_NN(X=24, HL=[512, 256], Y=24)
    print("Neural Network initialized: 24 -> 512 -> 256 -> 24")
    print("\nTraining custom NN (printing progress)...")
    nn.train_nn(x=inputData, target=GAPoses, epochs=1000, lr=0.01)
    print("Custom NN training complete!")
    return nn

def display_custom_nn_input():
    """
    display_custom_nn_input prints out step 6 and creates a variable called test pose with the genRanPose funtion with a population size of 1. it 
    generates a random test pose, displays it visually, and then returns the pose.
    """

    print("\n" + "="*100)
    print("STEP 6: Display Custom NN Input")
    print("="*100)
    testPose = genRanPoses(popSize=1)[0]
    print("Generated random test pose. Displaying...")
    testPose = genRanPoses(popSize=1)[0]
    plot_spider_pose(testPose, title="Custom NN - Test Input")
    plt.pause(2)
    plt.close()
    return testPose

def display_custom_nn_output(nn, testPose):
    """
    display_custom_nn_output(testPose, nn, GATargetPoses) is the next helper function that is run in the main program. it prints out step 7 
    and runs a test pose through the custom neural network (nn) to get a predicted output pose,this displays the predicted pose visually, and 
    then return the result.
    """

    print("\n" + "="*100)
    print("STEP 7: Display Custom NN Output")
    print("="*100)
    predictedPose = nn.FF(testPose)
    print("Custom NN prediction generated. Displaying...")
    plot_spider_pose(predictedPose, title="Custom NN - Prediction Output")
    plt.pause(2)
    plt.close()
    return predictedPose

def display_training_pytorch_nn(inputData, GAPoses):
    """
    display_training_pytorch_nn(inputData, GAPoses) is step 8 in the main program imported from the helpers file. iy prints and runs the 
    run_pytorch_nn function that trains a PYTorch neural network and returns the trained model as an output.
    """

    print("\n" + "="*100)
    print("STEP 8: Training PyTorch Neural Network")
    print("="*100)
    pytorch_model = run_pytorch_nn(inputData, GAPoses, epochs=300, lr=0.01)
    print("PyTorch NN training complete!")
    return pytorch_model

def display_pytorch_nn_input():
    """
    display_pytorch_nn_input() is step 9 in the main program imported from the helpers file. this function displays the pytorch neural 
    netweok input and testPose2 variable is created from genRanPoses with a population size of 1. this will generate a random test pose. 
    and opens a visual display of the test pose as well as returning testpose2.
    """

    print("\n" + "="*100)
    print("STEP 9: Display PyTorch NN Input")
    print("="*100)
    testPose2 = genRanPoses(popSize=1)[0]
    print("Generated random test pose. Displaying...")
    plot_spider_pose(testPose2, title="PyTorch NN - Test Input")
    plt.pause(3)
    plt.close()
    return testPose2

def display_pytorch_nn_output(pytorch_model, testPose2):
    """
    display_pytorch_nn_output(testPose2, pytorch_model, GATargetPoses) is the final step 10 in the main program imported from the helpers 
    file. this function takes in the test pose, the trained pytorch model, and the target poses from the genetic algorithm. it runs the test 
    pose through the pytorch neural network to get a predicted output pose, displays the predicted pose visually, and then returns the result.
    """

    print("\n" + "="*100)
    print("STEP 10: Display PyTorch NN Output")
    print("="*100)
    pytorch_prediction = pytorch_model.predict(testPose2)
    print("PyTorch NN prediction generated. Displaying...")
    plot_spider_pose(pytorch_prediction, title="PyTorch NN - Prediction Output")
    plt.pause(3)
    plt.close()
    return pytorch_prediction

def display_all_steps_complete():
    """
    the final helper function is called display_all_steps_complete, which sprints out all steps complete into the main.
    """

    print("\n" + "="*100)
    print("ALL STEPS COMPLETE")
    print("="*100)